---
.travis.yml:
  forge_password: "V0IFY6wNJnpe9tP7fP6NTx6odQ1y/0VmHo/XgP7aupS3nyhJJnEkFeTTh1sFEnRiT1W1EL28qdtIEW6UwVGsKs4/xjpb6y56CEgXB4vnlybYJVbUr+ZCaYT+yiiCZLzmcBzIGHW+4T6yk35BPOcZPSh8JgmTLxnoBhevSTflc44="
